@hostname = 127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@apiVersion = v1.0



###
GET http://{{host}}/api/{{apiVersion}}/categories

###
GET http://{{host}}/api/{{apiVersion}}/categories/3

###
POST http://{{host}}/api/{{apiVersion}}/categories
content-type: application/json

{
  "name": "test title"
}


###

POST http://{{host}}/api/{{apiVersion}}/users/register
content-type: application/json

{
  "username": "user3",
  "password": "test_password"
}

###
GET http://{{host}}/api/{{apiVersion}}/users?id=2
content-type: application/json

### 
GET http://{{host}}/api/{{apiVersion}}/users/current_user
content-type: application/json

# PASS TOKEN IN BODY