version: "3.9"

# Not tested. Will not work
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PASSWORD=YG
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./YG-server
    env_file:
      - ./YG-server/.env
    depends_on:
      - postgres
    # Volumes are to map the local disk to the container disk. If a change
    # happens in local disk it is also done in the container. Good for dev.
    # volumes:

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./yg-client
    ports:
      - 3000:3000
    env_file:
      - ./yg-client/.env
    # volumes: