version: "3.9"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    # restart: always
    # Volumes are to map the local disk to the container disk. If a change
    # happens in local disk it is also done in the container. Good for dev.
    volumes:
      # runs init_db.sql startup script
      - ./YG-server/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - pg.env

  server:
    build: ./YG-server
    depends_on:
      - db
    # links Implies 'depends_on'
    links:
      - db
    ports:
      - "5000:5000"
      # - 5000:5000
    env_file:
      - ./YG-server/.env

  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/config/nginx/nginx.conf
      - ./prod.conf:/config/nginx/site-confs/default
    environment:
      - PUID=1050
      - PGID=1050
      # - URL=...
      - SUBDOMAINS=${SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      # - TZ=Australia/Melboure
    depends_on:
      - server
      # - client

  # For Dev
  client:
    stdin_open: true
    depends_on: 
      - server
    links:
      - server
    build:
      dockerfile: Dockerfile.dev
      context: ./yg-client
    ports:
      - 3000:3000
    env_file:
      - ./yg-client/.env.local
      - ./yg-client/.env.development