-- Generated by TablePlus
-- Initialize the database before running the migrations

-- USE YG_DB;

-- USERS
-- Squences
-- CREATE SEQUENCE IF NOT EXISTS user_id_seq;

-- Table Definition
CREATE TABLE IF NOT EXISTS "user" (
    -- SERIAL is AUTO_INCREMENT
    "id" SERIAL NOT NULL,
    "auth_id" varchar NOT NULL,
    PRIMARY KEY ("id")
);

-- CHANNELS
-- Squences
-- CREATE SEQUENCE IF NOT EXISTS channel_id_seq;

-- Table Definition
CREATE TABLE IF NOT EXISTS "channel" (
    "id" SERIAL NOT NULL,
    "yt_channel_id" varchar NOT NULL,
    "name" varchar NOT NULL,
    PRIMARY KEY ("id")
);


-- RELATE user and channel
CREATE TABLE IF NOT EXISTS "user_channel" (
    "channel_id" int4,
    "user_id" int4,
    CONSTRAINT "user_channel_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel"("id") ON DELETE CASCADE,
    CONSTRAINT "user_channel_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE
);

-- CATEGORY
-- Squences
-- CREATE SEQUENCE IF NOT EXISTS category_id_seq;

-- Table Definition
CREATE TABLE IF NOT EXISTS "category" (
    "id" SERIAL NOT NULL,
    "name" varchar NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    "user_id" int4 NOT NULL,
    CONSTRAINT "category_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE,
    PRIMARY KEY ("id")
);



-- Relate channel and category
CREATE TABLE IF NOT EXISTS "channel_category" (
    "channel_id" int4,
    "category_id" int4,
    CONSTRAINT "channel_category_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE CASCADE,
    CONSTRAINT "channel_category_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel"("id") ON DELETE CASCADE
);


