"""User's auth_id is not nullable and is index

Revision ID: 68c9d30ecb79
Revises: 900e4bc0c1b3
Create Date: 2021-07-26 20:09:35.398008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c9d30ecb79'
down_revision = '900e4bc0c1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.create_index(op.f('ix_user_auth_id'), 'user', ['auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_id'), table_name='user')
    op.alter_column('user', 'auth_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
