"""User table now stores Auth0 ID

Revision ID: bd798f4510f6
Revises: 1832efff8b13
Create Date: 2021-07-26 16:09:34.636080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd798f4510f6'
down_revision = '1832efff8b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'username')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
