"""init_migration

Revision ID: 2abccb3f98c2
Revises: 
Create Date: 2021-06-11 13:18:20.703662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abccb3f98c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_user_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'channel', ['yt_channel_id'])
    op.alter_column('channel_category', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channel_category', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('channel_category_category_id_fkey', 'channel_category', type_='foreignkey')
    op.drop_constraint('channel_category_channel_id_fkey', 'channel_category', type_='foreignkey')
    op.create_foreign_key(None, 'channel_category', 'channel', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'channel_category', 'category', ['category_id'], ['id'])
    op.drop_column('channel_category', 'id')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.alter_column('user_channel', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_channel', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_channel_channel_id_fkey', 'user_channel', type_='foreignkey')
    op.drop_constraint('user_channel_user_id_fkey', 'user_channel', type_='foreignkey')
    op.create_foreign_key(None, 'user_channel', 'channel', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'user_channel', 'user', ['user_id'], ['id'])
    op.drop_column('user_channel', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channel', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user_channel', type_='foreignkey')
    op.drop_constraint(None, 'user_channel', type_='foreignkey')
    op.create_foreign_key('user_channel_user_id_fkey', 'user_channel', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_channel_channel_id_fkey', 'user_channel', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_channel', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_channel', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.add_column('channel_category', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'channel_category', type_='foreignkey')
    op.drop_constraint(None, 'channel_category', type_='foreignkey')
    op.create_foreign_key('channel_category_channel_id_fkey', 'channel_category', 'channel', ['channel_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('channel_category_category_id_fkey', 'channel_category', 'category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('channel_category', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channel_category', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'channel', type_='unique')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_user_id_fkey', 'category', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
