"""empty message

Revision ID: 2b6328e3f2c2
Revises: aac7a0a3de7c
Create Date: 2021-06-11 19:11:50.686372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6328e3f2c2'
down_revision = 'aac7a0a3de7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('category', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created', sa.DATE(), server_default=sa.text("'2021-06-06'::date"), autoincrement=False, nullable=False))
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
