@hostname = 127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@apiVersion = v1.0



###

########## CATEGORIES

# Get all categories from current user
GET http://{{host}}/api/{{apiVersion}}/categories

# TODO: send token

###

# Get specific category from current user
GET http://{{host}}/api/{{apiVersion}}/categories/3

# TODO: send token

# categories returned will belong to current user
## RETURNS
# {
#   "id": "3",
#   "name": "comedy",
#   "channels": ["pewdipie"]
# }


###

# Create category
POST http://{{host}}/api/{{apiVersion}}/categories
content-type: application/json

# TODO: send token

{
  "name": "cooking",
  "user_id": "2"
}


###

########## CHANNELS

# create channel and relate to category
POST http://{{host}}/api/{{apiVersion}}/channels
content-type: application/json

# TODO: send token

{
  "name": "simply dumpling",
  "yt_channel_id": "72f43a7b-d72a-4c18-8dac-ec6e2ed52702",
  "category_id": "4",
  "user_id": "2"
}

###
# get all channels of current user
GET http://{{host}}/api/{{apiVersion}}/channels

# TODO: send token in header
# {
#   "Authorization": "Bearer sdfsdf"
# }


# RETURNS
# {
#   [
#     {
#       "channel_id": "sdf", 
#       "name": "pewdiepie",
#       "categories": ["comedy", "gaming"]
#     },
#     {
#       "channel_id": "g8dsfgsd8g",
#       "name": "sam the cooking guy",
#       "categories": ["cooking", "food", "tutorials"]
#     },
#     {
#       "channel_id": "weg9h9w7df8v8x9",
#       "name": "Corey Schafer",
#       "categories": []
#     }
#   ]

# }

# Register user
POST http://{{host}}/api/{{apiVersion}}/users/register
content-type: application/json

{
  "username": "user3",
  "password": "test_password"
}

###

# Get specific user
GET http://{{host}}/api/{{apiVersion}}/users?id=2
content-type: application/json

### 

# Get current user
GET http://{{host}}/api/{{apiVersion}}/users/current_user
content-type: application/json

# TODO: PASS TOKEN IN BODY

###
